// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ExpenseTrack.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ExpenseTrack.Data
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<usp_ExpenseGroup_SelectResult>> usp_ExpenseGroup_SelectAsync(DateTime? CreatedDateFrom, DateTime? CreatedDateTo, int? BranchId, int? ExpenseStatusId, string SearchText, int? IndexStart, int? PageSize, string SortField, string OrderType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_GenerateCodeAsync(string TransactionCodeControlTypeDetail, int? RunningLenght, OutputParameter<string> Result, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
