// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTrackApi.Models
{
    [Table("Application", Schema = "ext")]
    public partial class Application
    {
        [Key]
        [StringLength(20)]
        [Unicode(false)]
        public string ApplicationCode { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string Year { get; set; }
        public int? BranchId { get; set; }
        public string SchoolName { get; set; }
        public string Address { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Status_id { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}