// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTrackApi.Models
{
    [Keyless]
    [Table("Employee", Schema = "ext")]
    public partial class Employee
    {
        [StringLength(10)]
        public string UserId { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}