// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTrack.Models
{
    [Table("ExpenseLog")]
    public partial class ExpenseLog
    {
        [Key]
        public Guid ExpenseLogId { get; set; }
        public Guid? ExpenseGroupId { get; set; }
        public int? ExpenseTypeId { get; set; }
        [StringLength(255)]
        public string ExpenseDetail { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string CreatedByCode { get; set; }
        [StringLength(255)]
        public string CreatedByName { get; set; }

        [ForeignKey("ExpenseGroupId")]
        [InverseProperty("ExpenseLogs")]
        public virtual ExpenseGroup ExpenseGroup { get; set; }
        [ForeignKey("ExpenseTypeId")]
        [InverseProperty("ExpenseLogs")]
        public virtual ExpenseLogType ExpenseType { get; set; }
    }
}