// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpenseTrackApi.Models
{
    public partial class usp_ExpenseGroup_SelectResult
    {
        public Guid? ExpenseGroupId { get; set; }
        public string ExpenseGroupCode { get; set; }
        public string ApplicationCode { get; set; }
        public string SchoolName { get; set; }
        public string ServicedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? TransferAmount { get; set; }
        public DateTime? ReviewedDate { get; set; }
        public DateTime? TransferDate { get; set; }
        public string TransferRemark { get; set; }
        public int? ExpenseStatusId { get; set; }
        public string ExpenseStatusName { get; set; }
        public string CancelledRemark { get; set; }
    }
}
