// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ExpenseTrackApi.DTOs.ExpenseTrack;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTrack.Models
{
    public partial class ExpenseItem
    {
        public static ExpenseItem NewExpenseItem(CreateExpenseTrackDetail detail, Guid? expenseGroupId)
        {
            ExpenseItem expenseItem = new ExpenseItem
            {
                ExpenseItemId = Guid.NewGuid(),
                ExpenseGroupId = expenseGroupId,
                CustomerDetailCode = detail.CustomerCode,
                CustomerName = detail.CustomerName,
                LevelRoom = detail.LevelRoom,
                IdentificationNo = detail.IdentificatiNo,
                CustomerTypeId = detail.CustomerTypeId,
                CustomerTypeName = detail.CustomerTypeName,
                StatusId = detail.StatusId,
                StatusName = detail.StatusName,
                Amount = detail.Amount,
                UpdatedDate = DateTime.Now
            };

            return expenseItem;
        }
    }
}