// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ExpenseTrackApi.DTOs.ExpenseTrack;
using Microsoft.EntityFrameworkCore;

namespace ExpenseTrack.Models
{
    public partial class ExpenseGroup
    {
        public static ExpenseGroup NewExpenseGroup(CreateExpenseTrackRequestDto input, string expenseGroupCode, int? userId, string userCode, string userName)
        {
            ExpenseGroup expenseGroup = new ExpenseGroup
            {
                ExpenseGroupId = Guid.NewGuid(),
                ExpenseGroupCode = expenseGroupCode,
                ApplicationCode = input.ApplicationCode,
                SchoolYear = input.ShcoolYear,
                BranchId = input.BranchId,
                BranchName = input.BranchName,
                SchoolName = input.ShcoolName,
                PayeeBankId = input.PayeeBankId,
                PayeeBankName = input.PayeeBankName,
                PayeeAccountNumber = input.PayeeAccountNumber,
                PayeeAccountName = input.PayeeAccountName,
                ServicedBranchId = input.ServiceBranchId,
                ServicedBranchName = input.ServiceBranchName,
                ServicedByUserId = input.ServiceByUserId,
                ServicedByCode = input.ServiceByCode,
                ServicedByName = input.ServiceByName,
                ItemCount = input.CreateExpenseTrackDetails.Count,
                TotalAmount = input.TotalAmount,
                DocumentCode = input.DocumentCode,
                DocumentId = input.DocumentId,
                ExpenseStatusId = 2,
                ZebraId = input.ZebraId,
                ZebraName = input.ZebraName,
                ReceiveDocTypeId = input.ReceiveDocTypeId,
                ReceiveDocTypeName = input.ReceiveDocTypeName
            };

            expenseGroup.SetCreatedDate(userId, userCode, userName);
            expenseGroup.SetUpdateDate(userId, userCode, userName);

            return expenseGroup;
        }

        public void SetCreatedDate(int? userId, string userCode, string userName)
        {
            CreatedDate = DateTime.Now;
            CreatedByUserId = userId;
            CreatedByCode = userCode;
            CreatedByName = userName;
            IsActive = true;
        }

        public void SetUpdateDate(int? userId, string userCode, string userName)
        {
            UpdatedDate = DateTime.Now;
            UpdatedByUserId = userId;
            UpdatedByCode = userCode;
            UpdatedByName = userName;
        }
    }
}